name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: python3 hello.py
      - run: zip hello.zip hello.py
      - uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.zip
